// Code generated by scripts/sync_shared_lib.py from shared/reporter/specs.go. DO NOT EDIT.

package main

import "fmt"

const (
	componentBinarySensor = "binary_sensor"
	componentSensor       = "sensor"
)

// entitySpec is one Home Assistant entity this reporter publishes.
type entitySpec struct {
	Key            string // object id suffix and the key inside the state payload
	Name           string
	Component      string
	DeviceClass    string
	EntityCategory string
	Icon           string
	Probe          probe
}

// The entity sets are deliberately small and chosen to survive upstream version
// changes. Every entity is backed either by an HTTP endpoint whose contract is
// documented by the upstream project, or by a metric whose absence resolves to
// unknown rather than to a confident wrong answer. Guessing at a richer set of
// series would produce entities that silently start lying after an upstream
// rename, which is worse than not having them.
func specsFor(app string) ([]entitySpec, error) {
	switch app {
	case "alloy":
		const base = "http://127.0.0.1:12345"
		return []entitySpec{
			{
				Key:         "ready",
				Name:        "Ready",
				Component:   componentBinarySensor,
				DeviceClass: "running",
				Probe:       probe{Kind: probeHTTPStatus, URL: base + "/-/ready"},
			},
			{
				Key:            "healthy",
				Name:           "Healthy",
				Component:      componentBinarySensor,
				DeviceClass:    "problem",
				EntityCategory: "diagnostic",
				Probe:          probe{Kind: probeHTTPStatus, URL: base + "/-/healthy"},
			},
			{
				Key:            "config_loaded",
				Name:           "Configuration loaded",
				Component:      componentBinarySensor,
				DeviceClass:    "problem",
				EntityCategory: "diagnostic",
				Probe: probe{
					Kind:   probeMetric,
					URL:    base + "/metrics",
					Metric: "alloy_config_last_load_successful",
				},
			},
			{
				Key:            "version",
				Name:           "Alloy version",
				Component:      componentSensor,
				EntityCategory: "diagnostic",
				Icon:           "mdi:tag-outline",
				Probe: probe{
					Kind:   probeMetricLabel,
					URL:    base + "/metrics",
					Metric: "alloy_build_info",
					Label:  "version",
				},
			},
		}, nil

	case "grafana_pdc":
		// The PDC agent's own series are not part of a documented contract, so
		// this stays with the endpoint the App's health check already trusts.
		// Tunnel registration state lives in Grafana Cloud, not in the agent.
		return []entitySpec{
			{
				Key:         "responding",
				Name:        "Agent responding",
				Component:   componentBinarySensor,
				DeviceClass: "running",
				Probe:       probe{Kind: probeHTTPStatus, URL: "http://127.0.0.1:8090/metrics"},
			},
		}, nil

	case "grafana_sm", "grafana_sm_browser":
		// The agent's /ready deliberately returns 503 until the probe has
		// connected to Grafana Cloud, which makes it the one endpoint that
		// distinguishes "process is up" from "probe is actually working".
		const base = "http://127.0.0.1:4050"
		return []entitySpec{
			{
				Key:         "running",
				Name:        "Probe running",
				Component:   componentBinarySensor,
				DeviceClass: "running",
				Probe:       probe{Kind: probeHTTPStatus, URL: base + "/"},
			},
			{
				Key:         "connected",
				Name:        "Connected to Grafana Cloud",
				Component:   componentBinarySensor,
				DeviceClass: "connectivity",
				Probe:       probe{Kind: probeHTTPStatus, URL: base + "/ready"},
			},
		}, nil
	}
	return nil, fmt.Errorf("no entity specification for App %q", app)
}
