#!/usr/bin/env python3
"""Copy the shared option validators into each App rootfs that uses them.

The image build context is the App directory, so a Dockerfile cannot COPY from
the repository root. Apps that need the shared library therefore carry a
generated copy under rootfs/usr/share/ha-lib/, kept in step with this script.
CI runs it with --check and rejects drift, the same contract the Synthetic
Monitoring variants use.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "shared" / "lib" / "ha-validate.sh"
DESTINATION = Path("rootfs/usr/share/ha-lib/ha-validate.sh")
CONSUMERS = ("alloy", "grafana_pdc")

# The MQTT reporter is a Go module rather than a shell library, so it is copied
# verbatim into every App that publishes Home Assistant entities. Tests stay in
# the source tree: they are run once from shared/reporter and would only add
# weight to four build contexts.
REPORTER_SOURCE = ROOT / "shared" / "reporter"
REPORTER_DESTINATION = Path("reporter")
REPORTER_CONSUMERS = ("alloy", "grafana_pdc", "grafana_sm", "grafana_sm_browser")

BANNER = (
    "# GENERATED FILE - DO NOT EDIT.\n"
    "# Source: shared/lib/ha-validate.sh\n"
    "# Regenerate: python3 scripts/sync_shared_lib.py\n"
)


def expected_content() -> bytes:
    body = SOURCE.read_text()
    # Keep the shell mode line first so ShellCheck and editors still classify
    # the generated copy, then state its provenance before anything else.
    first_line, _, remainder = body.partition("\n")
    return f"{first_line}\n{BANNER}{remainder}".encode()


def reporter_body(source: Path) -> bytes:
    """One reporter source as it should appear in an App build context."""
    if source.suffix != ".go":
        # go.sum has no comment syntax, and a marker in go.mod would be at the
        # mercy of whatever `go mod tidy` decides to do with it.
        return source.read_bytes()
    # Go's convention: the marker matches ^// Code generated .* DO NOT EDIT\.$
    # and sits before the package clause. The blank line matters - without it
    # the marker would be absorbed into the package doc comment.
    marker = (
        f"// Code generated by scripts/sync_shared_lib.py from "
        f"shared/reporter/{source.name}. DO NOT EDIT.\n\n"
    )
    return marker.encode() + source.read_bytes()


def reporter_files() -> dict[Path, bytes]:
    """The reporter sources each consuming App needs in its build context."""
    result: dict[Path, bytes] = {}
    for source in sorted(REPORTER_SOURCE.iterdir()):
        if not source.is_file() or source.name.endswith("_test.go"):
            continue
        # Only module sources travel. Anything else in the directory is a local
        # build artifact and must never reach an image build context.
        if source.name not in {"go.mod", "go.sum"} and source.suffix != ".go":
            continue
        result[REPORTER_DESTINATION / source.name] = reporter_body(source)
    return result


def synchronize(check: bool) -> int:
    content = expected_content()
    stale: list[str] = []
    for slug in CONSUMERS:
        destination = ROOT / slug / DESTINATION
        if destination.exists() and destination.read_bytes() == content:
            continue
        stale.append(str(destination.relative_to(ROOT)))
        if not check:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(content)

    reporter = reporter_files()
    for slug in REPORTER_CONSUMERS:
        expected_paths = {ROOT / slug / relative for relative in reporter}
        for relative, body in reporter.items():
            destination = ROOT / slug / relative
            if destination.exists() and destination.read_bytes() == body:
                continue
            stale.append(str(destination.relative_to(ROOT)))
            if not check:
                destination.parent.mkdir(parents=True, exist_ok=True)
                destination.write_bytes(body)
        # A source file removed upstream has to disappear from the App copies
        # too, or a stale build would keep compiling it.
        reporter_dir = ROOT / slug / REPORTER_DESTINATION
        if reporter_dir.is_dir():
            for existing in sorted(reporter_dir.iterdir()):
                if existing.is_file() and existing not in expected_paths:
                    stale.append(str(existing.relative_to(ROOT)))
                    if not check:
                        existing.unlink()

    if stale and check:
        print("Generated shared library copies are stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run: python3 scripts/sync_shared_lib.py", file=sys.stderr)
        return 1
    if stale:
        print(f"Synchronized {len(stale)} generated files")
    else:
        print("Shared library copies already synchronized")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of rewriting stale generated files",
    )
    args = parser.parse_args()
    return synchronize(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
