#!/usr/bin/env bash
# Generates the Alloy config from environment variables and writes it to stdout.
# NOTE: plain bash (NOT with-contenv) — this is invoked by init-alloy/run, which
# already has the container env and exports the options as env vars. with-contenv
# would reset the environment and wipe those exported values.
# Inputs are exported by init-alloy/run. OPERATION_MODE is fleet, local, or the
# upgrade-only legacy-hybrid value. Boolean inputs are "true"/"false" strings.
# Passwords are NOT interpolated here; the config references sys.env("LOKI_PASSWORD"),
# sys.env() so secrets never land on disk.
set -eu

LOG_LEVEL="${LOG_LEVEL:-info}"
OPERATION_MODE="${OPERATION_MODE:-legacy-hybrid}"
JOURNAL_PATH="${JOURNAL_PATH:-/var/log/journal}"
LOKI_URL="${LOKI_URL:-}"
LOKI_USERNAME="${LOKI_USERNAME:-}"
LOGS_SYSTEM="${LOGS_SYSTEM:-true}"
LOGS_HOMEASSISTANT="${LOGS_HOMEASSISTANT:-true}"
LOGS_ADDONS="${LOGS_ADDONS:-true}"
LOGS_EXCLUDE_ADDONS="${LOGS_EXCLUDE_ADDONS:-alloy}"
LOGS_MAX_AGE="${LOGS_MAX_AGE:-24h}"
PROMETHEUS_URL="${PROMETHEUS_URL:-}"
PROMETHEUS_USERNAME="${PROMETHEUS_USERNAME:-}"
INSTANCE_NAME="${INSTANCE_NAME:-homeassistant}"
METRICS_SCRAPE_INTERVAL="${METRICS_SCRAPE_INTERVAL:-60s}"
HOST_METRICS="${HOST_METRICS:-true}"
HOMEASSISTANT_METRICS="${HOMEASSISTANT_METRICS:-false}"
ALLOY_METRICS="${ALLOY_METRICS:-true}"
TEMPO_URL="${TEMPO_URL:-}"
TEMPO_USERNAME="${TEMPO_USERNAME:-}"
TRACES_ENABLED="${TRACES_ENABLED:-false}"
TRACES_NETWORK_ACCESS="${TRACES_NETWORK_ACCESS:-false}"
PYROSCOPE_URL="${PYROSCOPE_URL:-}"
PYROSCOPE_USERNAME="${PYROSCOPE_USERNAME:-}"
ALLOY_PROFILING="${ALLOY_PROFILING:-false}"
FLEET_URL="${FLEET_URL:-}"
FLEET_USERNAME="${FLEET_USERNAME:-}"
FLEET_COLLECTOR_NAME="${FLEET_COLLECTOR_NAME:-}"
FLEET_ATTRIBUTES="${FLEET_ATTRIBUTES:-}"
FLEET_POLL_FREQUENCY="${FLEET_POLL_FREQUENCY:-1m}"
ADDITIONAL_CONFIG="${ADDITIONAL_CONFIG:-}"
FLEET_REFERENCE_PIPELINE="${FLEET_REFERENCE_PIPELINE:-false}"

# A Fleet starter pipeline is rendered from the same controls as Local mode,
# but it runs inside Fleet's remote controller. It must not contain another
# remotecfg block or process-global logging configuration.
pipeline_enabled() {
  [ "${OPERATION_MODE}" != "fleet" ] || [ "${FLEET_REFERENCE_PIPELINE}" = "true" ]
}

pipeline_secret() {
  if [ "${FLEET_REFERENCE_PIPELINE}" = "true" ]; then
    printf '%s' GCLOUD_RW_API_KEY
  else
    printf '%s' "$1"
  fi
}

# Emit a basic_auth block when a username is set; a no-op otherwise.
# The password is referenced by env var name, never by value.
# $1 = username, $2 = name of the env var holding the password, $3 = indent
emit_basic_auth() {
  [ -n "$1" ] || return 0
  printf '\n%sbasic_auth {\n%s  username = "%s"\n%s  password = sys.env("%s")\n%s}\n' \
    "$3" "$3" "$1" "$3" "$2" "$3"
}

# Emit the App's targeting attribute plus a comma-separated key=value list.
# Input format is validated in init-alloy/run, so pairs are well-formed here.
# $1 = attribute list, $2 = indent
emit_attributes() {
  printf '%sattributes     = {\n' "$2"
  printf '%s  "ha_addon_instance" = "%s",\n' "$2" "${INSTANCE_NAME}"
  if [ -n "$1" ]; then
    local -a pairs
    IFS=',' read -r -a pairs <<<"$1"
    local pair
    for pair in "${pairs[@]}"; do
      printf '%s  "%s" = "%s",\n' "$2" "${pair%%=*}" "${pair#*=}"
    done
  fi
  printf '%s}\n' "$2"
}

if [ "${FLEET_REFERENCE_PIPELINE}" != "true" ]; then
cat <<ALLOYCONFIG
// Grafana Alloy config - auto-generated by HAOS add-on
// Do not edit directly - configure through the ingress Web UI

logging {
  level = "${LOG_LEVEL}"
}
ALLOYCONFIG
fi

if [ "${FLEET_REFERENCE_PIPELINE}" != "true" ] && [ "${OPERATION_MODE}" != "local" ] && [ -n "${FLEET_URL}" ]; then
cat <<ALLOYCONFIG

// --- Grafana Fleet Management (remote configuration) ---
// Alloy polls this endpoint and runs the returned configuration in a separate
// controller, alongside the locally generated pipelines below. The fetched config
// is cached under --storage.path, so it survives restarts and connectivity loss.
remotecfg {
  url            = "${FLEET_URL}"
  id             = "${INSTANCE_NAME}"
ALLOYCONFIG

if [ -n "${FLEET_COLLECTOR_NAME}" ]; then
  printf '  name           = "%s"\n' "${FLEET_COLLECTOR_NAME}"
fi

emit_attributes "${FLEET_ATTRIBUTES}" "  "

cat <<ALLOYCONFIG
  poll_frequency = "${FLEET_POLL_FREQUENCY}"
ALLOYCONFIG

emit_basic_auth "${FLEET_USERNAME}" GCLOUD_RW_API_KEY "  "

cat <<ALLOYCONFIG
}
ALLOYCONFIG
fi

if pipeline_enabled && [ -n "${LOKI_URL}" ]; then
cat <<ALLOYCONFIG

// --- Read systemd journal ---
loki.source.journal "journal" {
  path         = "${JOURNAL_PATH}"
  max_age      = "${LOGS_MAX_AGE}"
  forward_to   = [loki.process.journal.receiver]
  relabel_rules = loki.relabel.journal.rules
  labels       = {
    job = "systemd-journal",
  }
}

// --- Relabel journal fields ---
loki.relabel "journal" {
  forward_to = []
ALLOYCONFIG

if [ "${LOGS_SYSTEM}" != "true" ]; then
cat <<'ALLOYCONFIG'
  rule {
    source_labels = ["__journal_container_name"]
    regex         = "^$"
    action        = "drop"
  }
ALLOYCONFIG
fi

if [ "${LOGS_HOMEASSISTANT}" != "true" ]; then
cat <<'ALLOYCONFIG'
  rule {
    source_labels = ["__journal_container_name"]
    regex         = "^homeassistant$"
    action        = "drop"
  }
ALLOYCONFIG
fi

if [ "${LOGS_ADDONS}" != "true" ]; then
cat <<'ALLOYCONFIG'
  rule {
    source_labels = ["__journal_container_name"]
    regex         = "^addon_.*$"
    action        = "drop"
  }
ALLOYCONFIG
fi

if [ -n "${LOGS_EXCLUDE_ADDONS}" ]; then
  excluded_regex=""
  IFS=',' read -r -a excluded_addons <<<"${LOGS_EXCLUDE_ADDONS}"
  for addon in "${excluded_addons[@]}"; do
    [ -n "${excluded_regex}" ] && excluded_regex+="|"
    excluded_regex+="addon_(?:[^_]+_)?${addon}"
  done
cat <<ALLOYCONFIG
  rule {
    source_labels = ["__journal_container_name"]
    regex         = "^(${excluded_regex})$"
    action        = "drop"
  }
ALLOYCONFIG
fi

cat <<ALLOYCONFIG
  rule {
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }
  rule {
    source_labels = ["__journal__hostname"]
    target_label  = "hostname"
  }
  rule {
    source_labels = ["__journal_syslog_identifier"]
    target_label  = "syslog_identifier"
  }
  rule {
    source_labels = ["__journal__transport"]
    target_label  = "transport"
  }
  rule {
    source_labels = ["__journal_container_name"]
    target_label  = "container_name"
  }
}

// --- Process journal logs ---
loki.process "journal" {
  stage.drop {
    expression = "^\\\\s*\$"
  }

  // Extract log level from Home Assistant log format:
  // "2026-03-18 19:02:30.204 INFO (MainThread) [component] message"
  stage.regex {
    expression = "[0-9]{2}:[0-9]{2}:[0-9]{2}[.0-9]* (?P<extracted_level>DEBUG|INFO|NOTICE|WARNING|WARN|ERROR|CRITICAL|FATAL) "
  }

  stage.labels {
    values = {
      level = "extracted_level",
    }
  }

  forward_to = [loki.write.loki.receiver]
}

// --- Write to Loki ---
loki.write "loki" {
  endpoint {
    url = "${LOKI_URL}"
ALLOYCONFIG

emit_basic_auth "${LOKI_USERNAME}" "$(pipeline_secret LOKI_PASSWORD)" "    "

cat <<ALLOYCONFIG
  }
}
ALLOYCONFIG
fi

if pipeline_enabled && [ -n "${PROMETHEUS_URL}" ] && [ "${HOST_METRICS}" = "true" ]; then
cat <<ALLOYCONFIG

// --- Host metrics (node_exporter equivalent) ---
// CPU/mem/diskstats are host-wide (not namespaced); host_network gives real NIC
// stats; the filesystem collector reports mapped HA volumes (data partition).
// The container overlay rootfs is excluded by the default fs_types_exclude.
prometheus.exporter.unix "host" {
  // procfs_path/sysfs_path stay at defaults: the non-namespaced files already
  // carry host-wide values, and host_network fixes the net-namespaced ones.
  disable_collectors = ["ipvs", "btrfs", "infiniband", "xfs", "zfs", "nfs", "nfsd", "mdadm"]

  filesystem {
    // Drop pseudo/virtual filesystems and the container's own plumbing.
    fs_types_exclude     = "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|tmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)\$"
    mount_points_exclude = "^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)(\$|/)"
    mount_timeout        = "5s"
  }

  netdev {
    device_exclude = "^(veth.*|docker.*|br-.*|lo|cali.*|hassio.*)\$"
  }
}

discovery.relabel "host" {
  targets = prometheus.exporter.unix.host.targets

  rule {
    target_label = "instance"
    replacement  = "${INSTANCE_NAME}"
  }
}

prometheus.scrape "host" {
  targets         = discovery.relabel.host.output
  forward_to      = [prometheus.remote_write.metrics.receiver]
  scrape_interval = "${METRICS_SCRAPE_INTERVAL}"
  job_name        = "integrations/node_exporter"
}
ALLOYCONFIG
fi

if pipeline_enabled && [ -n "${PROMETHEUS_URL}" ] && [ "${HOMEASSISTANT_METRICS}" = "true" ]; then
cat <<ALLOYCONFIG

// --- Home Assistant Core metrics ---
// Core's own Prometheus endpoint, reached through the Supervisor proxy. The
// token comes from SUPERVISOR_TOKEN, which the Supervisor injects because
// homeassistant_api is set in config.yaml, so it never appears in this file.
// Requires the \`prometheus\` integration to be enabled in Home Assistant.
prometheus.scrape "homeassistant" {
  targets = [
    {
      "__address__" = "supervisor:80",
      "instance"    = "${INSTANCE_NAME}",
    },
  ]
  forward_to      = [prometheus.remote_write.metrics.receiver]
  scrape_interval = "${METRICS_SCRAPE_INTERVAL}"
  metrics_path    = "/core/api/prometheus"
  bearer_token    = sys.env("SUPERVISOR_TOKEN")
  scheme          = "http"
  job_name        = "homeassistant"
}
ALLOYCONFIG
fi

if pipeline_enabled && [ -n "${PROMETHEUS_URL}" ] && [ "${ALLOY_METRICS}" = "true" ]; then
cat <<ALLOYCONFIG

// --- Alloy self-monitoring metrics ---
prometheus.scrape "alloy" {
  targets = [{
    "__address__" = "127.0.0.1:12345",
    "instance"    = "${INSTANCE_NAME}",
  }]
  forward_to      = [prometheus.remote_write.metrics.receiver]
  scrape_interval = "${METRICS_SCRAPE_INTERVAL}"
  metrics_path    = "/metrics"
  job_name        = "integrations/alloy"
}
ALLOYCONFIG
fi

if pipeline_enabled && [ -n "${PROMETHEUS_URL}" ]; then
cat <<ALLOYCONFIG

// --- Write to Prometheus ---
prometheus.remote_write "metrics" {
  endpoint {
    url = "${PROMETHEUS_URL}"
ALLOYCONFIG

emit_basic_auth "${PROMETHEUS_USERNAME}" "$(pipeline_secret PROMETHEUS_PASSWORD)" "    "

cat <<ALLOYCONFIG
  }
}
ALLOYCONFIG
fi

if pipeline_enabled && [ "${TRACES_ENABLED}" = "true" ] && [ -n "${TEMPO_URL}" ]; then
  traces_listen_address="127.0.0.1"
  [ "${TRACES_NETWORK_ACCESS}" = "true" ] && traces_listen_address="0.0.0.0"
  if [ -n "${TEMPO_USERNAME}" ]; then
cat <<ALLOYCONFIG

otelcol.auth.basic "tempo" {
  username = "${TEMPO_USERNAME}"
  password = sys.env("$(pipeline_secret TEMPO_PASSWORD)")
}
ALLOYCONFIG
  fi

cat <<ALLOYCONFIG

// --- Receive OTLP traces and forward them to Tempo ---
otelcol.receiver.otlp "local" {
  grpc {
    endpoint = "${traces_listen_address}:4317"
  }
  http {
    endpoint = "${traces_listen_address}:4318"
  }
  output {
    traces = [otelcol.exporter.otlphttp.tempo.input]
  }
}

otelcol.exporter.otlphttp "tempo" {
  client {
    endpoint = "${TEMPO_URL}"
ALLOYCONFIG
  if [ -n "${TEMPO_USERNAME}" ]; then
    printf '    auth = otelcol.auth.basic.tempo.handler\n'
  fi
cat <<'ALLOYCONFIG'
  }
}
ALLOYCONFIG
fi

if pipeline_enabled && [ "${ALLOY_PROFILING}" = "true" ] && [ -n "${PYROSCOPE_URL}" ]; then
cat <<ALLOYCONFIG

// --- Continuously profile Alloy itself ---
pyroscope.scrape "alloy" {
  targets = [{
    "__address__" = "127.0.0.1:12345",
    "service_name" = "alloy",
  }]
  forward_to = [pyroscope.write.profiles.receiver]
}

pyroscope.write "profiles" {
  endpoint {
    url = "${PYROSCOPE_URL}"
ALLOYCONFIG
emit_basic_auth "${PYROSCOPE_USERNAME}" "$(pipeline_secret PYROSCOPE_PASSWORD)" "    "
cat <<'ALLOYCONFIG'
  }
}
ALLOYCONFIG
fi

if [ "${FLEET_REFERENCE_PIPELINE}" != "true" ] && pipeline_enabled \
  && [ -n "${ADDITIONAL_CONFIG}" ] && [ "${ADDITIONAL_CONFIG}" != "null" ]; then
  printf '\n// --- Additional user config ---\n%s\n' "${ADDITIONAL_CONFIG}"
fi
