#!/usr/bin/env bash
# Generates the Alloy config from environment variables and writes it to stdout.
# NOTE: plain bash (NOT with-contenv) — this is invoked by init-alloy/run, which
# already has the container env and exports the options as env vars. with-contenv
# would reset the environment and wipe those exported values.
# Inputs (env): LOG_LEVEL, JOURNAL_PATH, LOKI_URL, LOKI_USERNAME, PROMETHEUS_URL,
#   PROMETHEUS_USERNAME, INSTANCE_NAME, METRICS_SCRAPE_INTERVAL, ADDITIONAL_CONFIG.
# Passwords are NOT interpolated here; the config references sys.env("LOKI_PASSWORD")
# and sys.env("PROMETHEUS_PASSWORD") so the secrets never land on disk.
set -eu

LOG_LEVEL="${LOG_LEVEL:-info}"
JOURNAL_PATH="${JOURNAL_PATH:-/var/log/journal}"
LOKI_URL="${LOKI_URL:-}"
LOKI_USERNAME="${LOKI_USERNAME:-}"
PROMETHEUS_URL="${PROMETHEUS_URL:-}"
PROMETHEUS_USERNAME="${PROMETHEUS_USERNAME:-}"
INSTANCE_NAME="${INSTANCE_NAME:-homeassistant}"
METRICS_SCRAPE_INTERVAL="${METRICS_SCRAPE_INTERVAL:-60s}"
ADDITIONAL_CONFIG="${ADDITIONAL_CONFIG:-}"

# Emit a basic_auth block when a username is set; a no-op otherwise.
# The password is referenced by env var name, never by value.
# $1 = username, $2 = name of the env var holding the password, $3 = indent
emit_basic_auth() {
  [ -n "$1" ] || return 0
  printf '\n%sbasic_auth {\n%s  username = "%s"\n%s  password = sys.env("%s")\n%s}\n' \
    "$3" "$3" "$1" "$3" "$2" "$3"
}

cat <<ALLOYCONFIG
// Grafana Alloy config - auto-generated by HAOS add-on
// Do not edit directly - configure via add-on options

logging {
  level = "${LOG_LEVEL}"
}
ALLOYCONFIG

if [ -n "${LOKI_URL}" ]; then
cat <<ALLOYCONFIG

// --- Read systemd journal ---
loki.source.journal "journal" {
  path         = "${JOURNAL_PATH}"
  forward_to   = [loki.process.journal.receiver]
  relabel_rules = loki.relabel.journal.rules
  labels       = {
    job = "systemd-journal",
  }
}

// --- Relabel journal fields ---
loki.relabel "journal" {
  forward_to = []

  rule {
    source_labels = ["__journal__systemd_unit"]
    target_label  = "unit"
  }
  rule {
    source_labels = ["__journal__hostname"]
    target_label  = "hostname"
  }
  rule {
    source_labels = ["__journal_syslog_identifier"]
    target_label  = "syslog_identifier"
  }
  rule {
    source_labels = ["__journal__transport"]
    target_label  = "transport"
  }
  rule {
    source_labels = ["__journal_container_name"]
    target_label  = "container_name"
  }
}

// --- Process journal logs ---
loki.process "journal" {
  stage.drop {
    expression = "^\\\\s*\$"
  }

  // Extract log level from Home Assistant log format:
  // "2026-03-18 19:02:30.204 INFO (MainThread) [component] message"
  stage.regex {
    expression = "[0-9]{2}:[0-9]{2}:[0-9]{2}[.0-9]* (?P<extracted_level>DEBUG|INFO|NOTICE|WARNING|WARN|ERROR|CRITICAL|FATAL) "
  }

  stage.labels {
    values = {
      level = "extracted_level",
    }
  }

  forward_to = [loki.write.loki.receiver]
}

// --- Write to Loki ---
loki.write "loki" {
  endpoint {
    url = "${LOKI_URL}"
ALLOYCONFIG

emit_basic_auth "${LOKI_USERNAME}" LOKI_PASSWORD "    "

cat <<ALLOYCONFIG
  }
}
ALLOYCONFIG
fi

if [ -n "${PROMETHEUS_URL}" ]; then
cat <<ALLOYCONFIG

// --- Host metrics (node_exporter equivalent) ---
// CPU/mem/diskstats are host-wide (not namespaced); host_network gives real NIC
// stats; the filesystem collector reports mapped HA volumes (data partition).
// The container overlay rootfs is excluded by the default fs_types_exclude.
prometheus.exporter.unix "host" {
  // procfs_path/sysfs_path stay at defaults: the non-namespaced files already
  // carry host-wide values, and host_network fixes the net-namespaced ones.
  disable_collectors = ["ipvs", "btrfs", "infiniband", "xfs", "zfs", "nfs", "nfsd", "mdadm"]

  filesystem {
    // Drop pseudo/virtual filesystems and the container's own plumbing.
    fs_types_exclude     = "^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|tmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)\$"
    mount_points_exclude = "^/(dev|proc|run/credentials/.+|sys|var/lib/docker/.+)(\$|/)"
    mount_timeout        = "5s"
  }

  netdev {
    device_exclude = "^(veth.*|docker.*|br-.*|lo|cali.*|hassio.*)\$"
  }
}

discovery.relabel "host" {
  targets = prometheus.exporter.unix.host.targets

  rule {
    target_label = "instance"
    replacement  = "${INSTANCE_NAME}"
  }
}

prometheus.scrape "host" {
  targets         = discovery.relabel.host.output
  forward_to      = [prometheus.remote_write.metrics.receiver]
  scrape_interval = "${METRICS_SCRAPE_INTERVAL}"
  job_name        = "integrations/node_exporter"
}

prometheus.remote_write "metrics" {
  endpoint {
    url = "${PROMETHEUS_URL}"
ALLOYCONFIG

emit_basic_auth "${PROMETHEUS_USERNAME}" PROMETHEUS_PASSWORD "    "

cat <<ALLOYCONFIG
  }
}
ALLOYCONFIG
fi

if [ -n "${ADDITIONAL_CONFIG}" ] && [ "${ADDITIONAL_CONFIG}" != "null" ]; then
  printf '\n// --- Additional user config ---\n%s\n' "${ADDITIONAL_CONFIG}"
fi
